// Core Daily Check-In, Miss Penalty, Void Recovery, & Rank Promotion Logic for RankStreak

export const GOAL_DAYS_PER_RANK = 30; // 30 valid counted days per rank promotion

// Helper: Format Date object to local YYYY-MM-DD
export function getLocalDateString(dateObj = new Date()) {
  const year = dateObj.getFullYear();
  const month = String(dateObj.getMonth() + 1).padStart(2, '0');
  const day = String(dateObj.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

// Helper: Add N days to YYYY-MM-DD string
export function addDaysToDateString(dateStr, daysToAdd) {
  const [y, m, d] = dateStr.split('-').map(Number);
  const date = new Date(y, m - 1, d);
  date.setDate(date.getDate() + daysToAdd);
  return getLocalDateString(date);
}

// Helper: Calculate day difference between dateStr1 and dateStr2
export function getDaysDiff(dateStr1, dateStr2) {
  const [y1, m1, d1] = dateStr1.split('-').map(Number);
  const [y2, m2, d2] = dateStr2.split('-').map(Number);
  const t1 = new Date(y1, m1 - 1, d1).getTime();
  const t2 = new Date(y2, m2 - 1, d2).getTime();
  return Math.round((t2 - t1) / (1000 * 60 * 60 * 24));
}

/**
 * Calculates current recovery status for today based on past check-in history.
 * @param {Array} history - Array of { date, status, checked_in_at }
 * @param {string} todayStr - YYYY-MM-DD for current date
 * @returns {Object} { isRecovery: boolean, recoveryDaysLeft: number, lastMissedDate: string | null }
 */
export function getRecoveryStatus(history = [], todayStr = getLocalDateString()) {
  if (!history || history.length === 0) {
    return { isRecovery: false, recoveryDaysLeft: 0, lastMissedDate: null };
  }

  // Find all explicitly marked 'missed' days or implicit missed days
  const sorted = [...history].sort((a, b) => a.date.localeCompare(b.date));
  const missedEntries = sorted.filter(item => item.status === 'missed');
  
  if (missedEntries.length === 0) {
    return { isRecovery: false, recoveryDaysLeft: 0, lastMissedDate: null };
  }

  const lastMissed = missedEntries[missedEntries.length - 1];
  const diff = getDaysDiff(lastMissed.date, todayStr);

  // If today is within 1 or 2 days after the missed day (i.e. diff === 1 or diff === 2)
  if (diff === 1) {
    return { isRecovery: true, recoveryDaysLeft: 2, lastMissedDate: lastMissed.date };
  } else if (diff === 2) {
    return { isRecovery: true, recoveryDaysLeft: 1, lastMissedDate: lastMissed.date };
  }

  return { isRecovery: false, recoveryDaysLeft: 0, lastMissedDate: null };
}

/**
 * Evaluates state and automatically injects missed entries for any un-checked calendar days between start and today.
 */
export function evaluateMissedDays(history = [], createdDateStr = getLocalDateString(), todayStr = getLocalDateString()) {
  const updatedHistory = [...history];
  const historyMap = new Map(updatedHistory.map(item => [item.date, item]));

  // Sort history dates to find earliest active tracking date
  let startDate = createdDateStr;
  if (updatedHistory.length > 0) {
    const earliest = [...updatedHistory].sort((a, b) => a.date.localeCompare(b.date))[0].date;
    if (earliest < startDate) startDate = earliest;
  }

  let curr = startDate;
  while (curr < todayStr) {
    if (!historyMap.has(curr)) {
      // Unchecked past day! Evaluate if it was in recovery from a prior miss or a new miss
      const rec = getRecoveryStatus(updatedHistory, curr);
      const newStatus = rec.isRecovery ? 'void_recovery' : 'missed';
      const entry = {
        date: curr,
        status: newStatus,
        checked_in_at: null,
        autoGenerated: true
      };
      updatedHistory.push(entry);
      historyMap.set(curr, entry);
    }
    curr = addDaysToDateString(curr, 1);
  }

  return updatedHistory.sort((a, b) => a.date.localeCompare(b.date));
}

/**
 * Process a check-in action for today.
 */
export function executeCheckIn(state, todayStr = getLocalDateString()) {
  const { history = [], current_streak_days = 0, days_this_month = 0, current_rank = 1 } = state;
  
  // Make sure missed days are up to date
  const evaluatedHistory = evaluateMissedDays(history, state.created_at || todayStr, todayStr);
  const existingToday = evaluatedHistory.find(h => h.date === todayStr);

  if (existingToday && existingToday.checked_in_at) {
    // Already checked in today!
    return { ...state, alreadyCheckedIn: true };
  }

  // Check if today falls in recovery period
  const recoveryInfo = getRecoveryStatus(evaluatedHistory, todayStr);
  const status = recoveryInfo.isRecovery ? 'void_recovery' : 'counted';

  const newEntry = {
    date: todayStr,
    status,
    checked_in_at: new Date().toISOString()
  };

  const updatedHistory = evaluatedHistory.filter(h => h.date !== todayStr);
  updatedHistory.push(newEntry);
  updatedHistory.sort((a, b) => a.date.localeCompare(b.date));

  let newStreak = current_streak_days;
  let newMonthDays = days_this_month;
  let newRank = current_rank;
  let rankEvent = null; // 'promoted' | 'demoted' | null

  if (status === 'counted') {
    newStreak += 1;
    newMonthDays += 1;

    // Check Promotion (30 valid counted days reached)
    if (newMonthDays >= GOAL_DAYS_PER_RANK) {
      if (newRank < 15) {
        newRank += 1;
        rankEvent = 'promoted';
      }
      newMonthDays = 0; // Reset progress for next rank
    }
  }

  return {
    ...state,
    history: updatedHistory,
    current_streak_days: newStreak,
    days_this_month: newMonthDays,
    current_rank: newRank,
    rankEvent,
    lastCheckInStatus: status
  };
}

/**
 * Generates calendar month data structure for calendar view rendering.
 */
export function getMonthCalendarGrid(year, month, history = []) {
  const historyMap = new Map(history.map(h => [h.date, h]));
  const firstDayOfMonth = new Date(year, month - 1, 1);
  const daysInMonth = new Date(year, month, 0).getDate();
  const startingDayOfWeek = firstDayOfMonth.getDay(); // 0 = Sun

  const todayStr = getLocalDateString();
  const grid = [];

  // Blank slots before first day
  for (let i = 0; i < startingDayOfWeek; i++) {
    grid.push({ isBlank: true, id: `blank-${i}` });
  }

  for (let day = 1; day <= daysInMonth; day++) {
    const dStr = `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
    const checkin = historyMap.get(dStr);
    
    let status = 'none';
    if (checkin) {
      status = checkin.status; // 'counted', 'void_recovery', 'missed'
    }

    grid.push({
      dateStr: dStr,
      dayNumber: day,
      status,
      isCheckedIn: Boolean(checkin && checkin.checked_in_at),
      isToday: dStr === todayStr,
      isFuture: dStr > todayStr,
      isBlank: false
    });
  }

  return grid;
}
